-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "", mode = "preferred", position = "0x0", scale = 1.25 })
hl.monitor({ output = "DP-1", mode = "3840x2160@59.997", position = "0x0", scale = 1 })
hl.monitor({ output = "HDMI-A-1", mode = "3840x2160@60.000", position = "3840x0", scale = 1 })
hl.monitor({ output = "eDP-1", mode = "2304x1440@59.945", position = "0x0", scale = 1, vrr = 0 })
