augroup MyAutoCmd
  autocmd!
augroup END

" vim-plug
call plug#begin('~/.vim/plug')
" LSP
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'mattn/vim-lsp-icons'

Plug 'itchyny/lightline.vim'
Plug 'airblade/vim-gitgutter'
Plug 'flazz/vim-colorschemes'
Plug 'tpope/vim-commentary', { 'on': 'Commentary' }
Plug 'cohama/lexima.vim'
Plug 'tpope/vim-fugitive', { 'on': ['Gdiff', 'Gblame'] }
Plug 'thinca/vim-quickrun', { 'on': ['QuickRun'] }
Plug 'k0kubun/vim-open-github', { 'on': ['OpenGithub'] }

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

" TOML
Plug 'cespare/vim-toml', { 'for': 'toml' }

" Protocol Buffers
Plug 'uber/prototool', { 'for': 'proto', 'rtp': 'vim/prototool' }

" Golang
Plug 'mattn/vim-goimports', { 'for': 'go' }

" TypeScript
Plug 'leafgarland/typescript-vim', { 'for': 'typescript' }
Plug 'peitalin/vim-jsx-typescript', { 'for': 'typescript' }

" Coffee
Plug 'kchmck/vim-coffee-script', { 'for': 'coffee' }

" Re:View
Plug 'tokorom/vim-review', { 'for': 're' }

" Swift
Plug 'keith/swift.vim', { 'for': 'swift' }

" Kotlin
Plug 'udalov/kotlin-vim', { 'for': 'kotolin' }

" Terraform
Plug 'hashivim/vim-terraform', { 'for': 'tf' }

" Ocaml
Plug 'ocaml/vim-ocaml', { 'for': 'ocaml' }

call plug#end()

" Editor
set clipboard=unnamed
syntax enable
colorscheme molokai
set number
set tabstop=2 shiftwidth=2 softtabstop=2
set ignorecase
set smartcase

" Config
set noswapfile

nnoremap <silent> ;r :<C-u>QuickRun<CR>
nnoremap <silent> ;v :<C-u>OpenGithub<CR>
vnoremap <silent> ;v :<C-u>'<,'>OpenGithub<CR>

function! OcamlFmt()
  silent execute "!ocamlformat --enable-outside-detected-project --module-item-spacing=compact --inplace %"
  edit!
endfunction

command! OcamlFmt call OcamlFmt()
augroup ocaml_autocmd
  autocmd BufWritePost *.ml OcamlFmt
augroup END

" Source
source ~/.vim/rc/move.vimrc
source ~/.vim/rc/lightline.vimrc
source ~/.vim/rc/lsp.vim
source ~/.vim/rc/fzf.vim

let g:ruby_host_prog = '~/.anyenv/envs/rbenv/versions/2.7.2/bin/neovim-ruby-host'
