augroup MyAutoCmd
  autocmd!
augroup END

" vim-plug
call plug#begin('~/.vim/plug')
Plug 'itchyny/lightline.vim'
Plug 'airblade/vim-gitgutter'
Plug 'flazz/vim-colorschemes'
Plug 'tpope/vim-commentary', { 'on': 'Commentary' }
Plug 'cohama/lexima.vim'
Plug 'tpope/vim-fugitive', { 'on': ['Gdiff', 'Gblame'] }

" TOML
Plug 'cespare/vim-toml', { 'for': 'toml' }
call plug#end()

" Editor
set clipboard=unnamed
syntax enable
colorscheme molokai
set number

" Config
set noswapfile

" Source
source ~/.vim/rc/move.vimrc
source ~/.vim/rc/lightline.vimrc
