[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo =  'itchyny/lightline.vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
