[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'neomake/neomake'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo =  'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'prabirshrestha/async.vim'
