[[plugins]]
repo = 'tpope/vim-commentary'
on_cmd = ['Commentary']

[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = ['Gdiff', 'Gblame']

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

##
## filetype
##
[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'uarun/vim-protobuf'
on_ft = 'proto'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'chr4/nginx.vim'
on_ft = 'nginx'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]]
repo = 'magicalbanana/sql-syntax-vim'
on_ft = 'sql'

[[plugins]]
repo = 'keith/swift.vim'
on_ft = 'swift'
