[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = ['QuickRun']
 
[[plugins]]
repo = 'tpope/vim-commentary'
on_cmd = ['Commentary']

[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = ['Gdiff', 'Gblame']

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'powerman/vim-plugin-viewdoc'
on_cmd = ['ViewDocMan']

# filetype
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'
