language: bash
os: osx
osx_image: xcode8.3  # OS X 10.12 (https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version)

sudo: required

addons:
  ssh_known_hosts:
    - github.com

env:
  global:
    MACHINE='travis'
    SKIP_TAGS='mas,ruby,golang,nodejs,vim'

before_install:
  - openssl aes-256-cbc -K $encrypted_d1b5d8cd2408_key -iv $encrypted_d1b5d8cd2408_iv -in travis.github.enc -out travis.github -d
  - mv travis.github ~/.ssh/id_rsa
  - chmod 0600 ~/.ssh/id_rsa

script:
  - bash script/bootstrap --skip-tags="$SKIP_TAGS" -vvvv
