language: bash
os: osx
osx_image: xcode8.3  # OS X 10.12 (https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version)

sudo: required

addons:
  ssh_known_hosts:
    - github.com

env:
  global:
    MACHINE='travis'
    SKIP_TAGS='mas,ruby,golang,nodejs,vim'

script:
  - bash script/bootstrap --skip-tags="$SKIP_TAGS" -vvvv
