language: bash
os: osx

sudo: required

env:
  global:
    MACHINE='travis'

before_install:
  - openssl aes-256-cbc -K $encrypted_d1b5d8cd2408_key -iv $encrypted_d1b5d8cd2408_iv -in travis.github.enc -out travis.github -d

script:
  - bash script/bootstrap
