homebrew:
  repositories:
    - potsbo/tools 

  applications:
    - iterm2
    - sourcetree
    - skype
    - atom
    - postgres
    - spotify
    - dropbox
    - docker
    - jetbrains-toolbox
    - google-chrome
    - google-japanese-ime
    - keytype

  packages:
    - peco
    - hub
    - jq
    - wget
    - envchain
