- name:       development environment
  hosts:      127.0.0.1
  connection: local
  vars:
    home_path:     '{{ lookup("env", "HOME") }}'
    dotfiles_path: '{{ home_path }}/.dotfiles'
    src_path: '{{ home_path }}/src'

  vars_files:
    - config.yml

  roles:
    - role: anyenv
      tags: ['install', 'anyenv']

    - role: homebrew
      tags: ['install', 'homebrew']

    - role: ruby
      tags: ['language', 'ruby']

    - role: golang
      tags: ['language', 'golang']

    - role: tmux
      tags: ['install', 'tmux']

    - role: zsh
      tags: ['install', 'zsh']

    - role: link
      tags: ['link']

    - role: vim
      tags: ['vim']
