- name:       development environment
  hosts:      127.0.0.1
  connection: local
  vars:
    home_path:     '{{ lookup("env", "HOME") }}'
    dotfiles_path: '{{ home_path }}/.dotfiles'
  vars_files:
    - config.yml

  roles:
    - role: homebrew
      tags: ['install', 'homebrew']

    - role: link
      tags: ['link']
