- name: clone
  git:
    repo: 'https://{{ clone.repo }}'
    dest: '{{ src_path }}/{{ clone.repo }}'
    update: no

- name: install
  copy:
    src: '{{ item }}'
    dest: '{{ clone.dest }}/{{ item | basename }}'
  with_fileglob: '{{ src_path }}/{{ clone.repo }}/*/*.ttf '
