- name: check rbenv
  command: |
    bash -lc 'which rbenv'
  register: which_rbenv
  changed_when: False
  ignore_errors: yes

- name: install rbenv
  command: |
    bash -lc 'echo $PATH; echo $HOME; ls -la ~/.anyenv/; anyenv install rbenv'
  when: which_rbenv.rc > 0

- name: install plugins
  git:
    repo: 'https://{{ item }}'
    dest: '{{ ruby.plugins_dir }}/{{ item | basename }}'
    update: no
  with_items: '{{ ruby.plugins }}'
  when: ruby.plugins_dir and ruby.plugins

- name: add links
  file:
    src:   '{{ dotfiles_path }}/{{ item.key }}'
    dest:  '{{ home_path }}/{{ item.value }}'
    state: link
    force: yes
  loop_control:
    label: '{{ item.value }}'
  with_dict: '{{ ruby.links }}'

- name: get installed versions
  command: |
    bash -lc 'rbenv versions'
  changed_when: False
  register: installed_versions

- name: install ruby
  command: |
    bash -lc 'rbenv install {{ item | quote }}'
  when: |
    ruby.versions and installed_versions.stdout.find(item) == -1
  with_items: '{{ ruby.versions }}'

- name: get global version
  command: |
    bash -lc 'rbenv global'
  register: global_ruby
  changed_when: False

- name: set global ruby
  command: |
    bash -lc 'rbenv global {{ ruby.versions[0] | quote }}'
  when: global_ruby.stdout != ruby.versions[0]
