- name: install oh-my-zsh
  git:
    repo: 'https://{{ zsh.manager }}'
    dest: '{{ src_path }}/{{ zsh.manager }}'
    update: no

- name: create zsh symlink
  file:
    src:   '{{ src_path }}/{{ zsh.manager }}'
    dest:  '{{ zsh.directory }}'
    state: link
    force: yes

- name: install plugin
  git:
    repo: 'https://{{ item }}'
    dest: '{{ src_path }}/{{ item }}'
    update: no
  with_items: '{{ zsh.plugins }}'

- name: link plugin
  file:
    src:   '{{ src_path }}/{{ item }}'
    dest:  '{{ zsh.directory }}/custom/plugins/{{ item | basename }}'
    state: link
    force: yes
  with_items: '{{ zsh.plugins }}'

- name: install themes
  git:
    repo: 'https://{{ item }}'
    dest: '{{ src_path }}/{{ item }}'
    update: no
  with_items: '{{ zsh.themes }}'

- name: allocate parent directories
  file:
    dest:    '{{ zsh.directory }}/custom/themes/'
    state:   directory
    recurse: yes

- name: link themes
  file:
    src:   '{{ src_path }}/{{ item }}'
    dest:  '{{ zsh.directory }}/custom/themes/{{ item | basename }}'
    state: link
    force: yes
  with_items: '{{ zsh.themes }}'
