- name: check rustc
  command: |
    bash -lc 'which rustc'
  register: rustc
  changed_when: False
  ignore_errors: yes

- name: install rust
  command: |
    bash -lc 'curl https://sh.rustup.rs -sSf | sh -s -- -y'
  when: rustc.rc > 0
