- name: check rustc
  command: |
    bash -lc 'which rustc'
  register: rustc
  changed_when: False
  ignore_errors: yes

- name: install rust
  command: |
    bash -lc "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
  when: rustc.rc > 0
