- name: check signin
  command: |
    bash -lc 'mas account'
  register: mas_already_signin
  changed_when: False

- name: signin to mas
  command: |
    bash -lc 'mas signin --dialog {{ mas.appstore_id | quote }}'
  ignore_errors: yes
  register: mas_signin
  when: mas.appstore_id and mas_already_signin.rc > 0

- name: get installed applications
  command: |
    bash -lc 'ls /Applications'
  changed_when: False
  register: installed_applications

- name: install applications
  command: |
    bash -lc 'mas install {{ item.value | quote }}'
  loop_control:
    label: '{{ item.key }}'
  when: mas.applications and ( mas_already_signin.rc == 0 or mas_signin.get('rc') == 0 ) and item.key not in installed_applications.stdout_lines
  with_dict: '{{ mas.applications }}'
