- name: check signin
  command: |
    bash -lc 'mas account'
  register: mas_already_signin
  changed_when: False

- name: signin to mas
  command: |
    bash -lc 'mas signin --dialog {{ mas.appstore_id | quote }}'
  ignore_errors: yes
  register: mas_signin
  when: mas.appstore_id and mas_already_signin.rc > 0

- name: install applications
  command: |
    bash -lc '[ -d /Applications/{{ item.key }} ] || mas install {{ item.value | quote }}'
  loop_control:
    label: '{{ item.key }}'
  with_dict: '{{ mas.applications }}'
  when: mas.applications and ( mas_already_signin.rc == 0 or mas_signin.get('rc') == 0 )
