brew "aqua"
brew "ijq"
brew "reattach-to-user-namespace"
brew "tree"
brew "watch"
brew "coreutils"
brew "tmux"
brew "libyaml" # for ruby build
cask "akiflow"
cask "karabiner-elements"
cask "visual-studio-code"
cask "google-japanese-ime"
cask "raycast"
cask "keyboard-cleaner"
cask "zoom"
cask "dash"
cask "docker"
cask "1password"
cask "notion"
cask "notion-calendar"
cask "google-cloud-sdk"
cask "font-monaspace-nerd-font"
cask "tailscale"
cask "ghostty"
cask "cursor"
cask "zotero"
mas "Magnet", id: 441258766
mas "Slack", id: 803453959
mas "Keynote", id: 409183694
