#!/bin/bash

set -eux

brew_check() {
  if brew info $1 | grep "Not installed" > /dev/null 2>&1
  then
    echo "  + Installing $1..."
    brew install $1
  else
    echo "  + $1 found."
  fi
}

link_check() {
  if [[ ! -f "$2" && ! -d "$2" && ! -L "$2" ]]; then
    ln -s $1 $2
  fi
}

# Config
SRC_DIR=$HOME/src
DOTFILES_DIR=$HOME/.dotfiles
TMUX_DIR=$HOME/.tmux

# PATH
export GOPATH=$HOME/.go
export PATH=$PATH:$GOPATH/bin

# Install brew
if test ! $(which brew); then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Check go
brew_check go
mkdir -p $GOPATH
mkdir -p $SRC_DIR
link_check $HOME/src $GOPATH/src

# ghq
go get github.com/motemen/ghq

# dotfiles
ghq get potsbo/dotfiles
link_check $SRC_DIR/github.com/potsbo/dotfiles $DOTFILES_DIR
CONFS=(.vimrc .zshrc .gitconfig .gitignore_global .tmux.conf .tmux-powerlinerc)
for conf in ${CONFS[@]}; do
  link_check $HOME/.dotfiles/$conf $HOME/$conf
done

# tmux
brew_check tmux
ghq get potsbo/tmux-powerline
mkdir -p $HOME/.tmux
link_check $SRC_DIR/github.com/potsbo/tmux-powerline $TMUX_DIR/tmux-powerline

# Tools
go get github.com/peco/peco
brew_check hub
brew_check jq
brew_check wget
brew_check rbenv
brew_check pyenv

if [ ! -d $HOME/.oh-my-zsh ]; then
  git clone git://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh
fi
