#!/usr/bin/env bash

set -eu
: ${DOTFILES_PATH:="$HOME/.go/src/github.com/potsbo/dotfiles"}

ARGS=('')
for a in "$@"; do
  ARGS=(${ARGS[@]} "$a")
done

ansible_check() {
  if brew info ansible | grep "Not installed" > /dev/null 2>&1
  then
    echo "    + Installing ansible..."
    brew install ansible
  else
    echo "    + ansible found."
  fi
}

install_brew() {
  echo "  + Homebrew"
  if test ! $(which brew); then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
    echo "    + Homebrew found."
  fi
}

link_check() {
  if [[ ! -f "$2" && ! -d "$2" && ! -L "$2" ]]; then
    ln -s $1 $2
  fi
}

check_name() {
  echo "  + Machine Name"
  MACHINE=${MACHINE:-$(hostname | sed -e 's/\.local//g')}
  if [[ $MACHINE =~ ^[a-z\-]+$ ]]; then
    echo "    + $MACHINE is valid."
  else
    echo "    + $MACHINE is not valid."
    exit 1
  fi
}

set_ssh_key() {
  echo "  + SSH key"

  KEYS=($MACHINE $MACHINE.github)
  for name in ${KEYS[@]}; do
    path=~/.ssh/$name
    if [[ ! -f "$path" && ! -L "$path" ]]; then
      ssh-keygen -f $path -t rsa -N ''
    else
      echo "      + $name exists."
    fi
    common_name=$(echo $name | sed "s/^$MACHINE/id_rsa/")
    echo "      + link ~/.ssh/$common_name to ~/.ssh/$name"
    link_check ~/.ssh/$name ~/.ssh/$common_name
  done
}

clone_or_update_repo() {
  local git_dir="$DOTFILES_PATH/.git"
  link_check $DOTFILES_PATH ~/.dotfiles

  if [ -d "$git_dir" ]; then
    echo 'Updating repo...'

    cd $DOTFILES_PATH

    if [ "$(git --git-dir="$git_dir" symbolic-ref --short HEAD 2> /dev/null)" != "master" ]; then
      echo 'skip (working on a non-master branch)'
      return
    fi

    if ! git --git-dir="$git_dir" diff --no-ext-diff --quiet --exit-code > /dev/null 2>&1; then
      echo 'skip (unstaged changes present)'
      return
    fi

    if ! git --git-dir="$git_dir" diff-index --cached --quiet HEAD -- > /dev/null 2>&1; then
      echo 'skip (uncommitted changes present)'
      return
    fi

    git --git-dir="$git_dir" pull origin master
    git --git-dir="$git_dir" submodule sync
    cd -
    echo 'done'
  elif ! [ -d "$DOTFILES_PATH" ]; then
    echo 'Cloning repo...'
    git clone --recursive https://github.com/potsbo/dotfiles.git --branch master $DOTFILES_PATH
    echo 'done'
  fi
}

check_xcode_license_approved() {
  echo 'Agreeing to Xcode license...'

  local has_error=0

  if ! [[ "$(/usr/bin/xcrun clang 2>&1 || true)" =~ 'license' ]]; then
    echo 'skip (already approved)'
    return
  fi

  sudo expect -c '
    set timeout 3
    spawn xcodebuild -license
    expect {
      timeout { exit 2 }
      -exact "for more" {
        send "G"
        exp_continue
      }
      -exact "agree, print, cancel" {
        send "agree\n"
        exp_continue
      }
      -exact "You can view the license agreements" {
        exit 0
      }
    }
  ' > /dev/null || has_error=1

  [ $has_error -eq 1 ] && sudo xcodebuild -license

  echo 'done'
}

check_xcode_license_approved
clone_or_update_repo
check_name
set_ssh_key
install_brew
ansible_check

# ansible
$DOTFILES_PATH/provisioning/run.sh ${ARGS[@]}
