#!/usr/bin/env bash

MACHINE_NAME=$(hostname -s)

if [[ $MACHINE_NAME =~ ^[a-z\-]+$ ]]; then
	exit 0
fi

new_maiche_name=$MACHINE_NAME

while ! [[ $new_maiche_name =~ ^[a-z\-]+$ ]]; do
	echo -n "Name this computer (current: $MACHINE_NAME) : "
	read new_maiche_name;
done

sudo hostname $new_maiche_name
