#!/usr/bin/env bash

ICLOUD_DRIVE=~/Library/Mobile\ Documents/com~apple~CloudDocs

UPLOAD_DIR="$ICLOUD_DRIVE/publickeys"
UPLOAD_PATH="${UPLOAD_DIR}/$(hostname -s).pub"

LOCAL_DIR=~/.local/ssh
LOCAL_PATH=$LOCAL_DIR/id

force_key_existence() {
	if [[ -f "$LOCAL_PATH" ]]; then
		return
	fi

	mkdir -p "$LOCAL_DIR"
	ssh-keygen -t ed25519 -f "$LOCAL_PATH" -N ''
}

force_publickey_shared() {
	mkdir -p "$UPLOAD_DIR"
	cp "$LOCAL_PATH.pub" "$UPLOAD_PATH"
}

force_key_existence
force_publickey_shared
