- name: install tmux-powerline
  git:
    repo: 'https://{{ item }}'
    dest: '{{ src_path }}/{{ item }}'
    update: no
  with_items: '{{ tmux.deps }}'

- name: check tmux directory
  file:
    dest:    '{{ tmux.directory }}'
    state:   directory
    recurse: yes

- name: create tmux-powerline symlink
  file:
    src:   '{{ src_path }}/{{ item }}'
    dest:  '{{ tmux.directory }}/{{ item | basename }}'
    state: link
    force: yes
  with_items: '{{ tmux.deps }}'
