- name: check vim directory
  file:
    dest:    '{{ vim.directory }}'
    state:   directory
    recurse: yes

- name: create symlinks
  file:
    src:   '{{ dotfiles_path }}/{{ item.key }}'
    dest:  '{{ home_path }}/{{ item.value }}'
    state: link
    force: yes
  loop_control:
    label: '{{ item.value }}'
  with_dict: '{{ vim.links }}'

- name: check autoload directory
  file:
    dest:    '{{ home_path }}/.local/share/nvim/site/autoload'
    state:   directory
    recurse: yes

- name: vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: '{{ home_path }}/.local/share/nvim/site/autoload/plug.vim'
