- name: check vim directory
  file:
    dest:    '{{ vim.directory }}'
    state:   directory
    recurse: yes

- name: create symlinks
  file:
    src:   '{{ dotfiles_path }}/{{ item.key }}'
    dest:  '{{ home_path }}/{{ item.value }}'
    state: link
    force: yes
  loop_control:
    label: '{{ item.value }}'
  with_dict: '{{ vim.links }}'
