- name: create directories
  file:
    dest:  '{{ home_path }}/{{ item }}'
    mode:  0700
    state: directory
  with_items:
    - '.ssh'
    - '.ssh/config.d'
    - '.ssh/keys'

- name: clone dotssh
  git:
    repo: 'https://{{ ssh.dotssh }}'
    dest: '{{ src_path }}/{{ ssh.dotssh }}'
    update: no

- name: install dotssh
  file:
    src:   '{{ item }}'
    dest:  '{{ home_path }}/.ssh/config.d/{{ item | basename }}'
    state: link
    force: yes
  with_fileglob:
    - '{{ src_path }}/{{ ssh.dotssh }}/config.d/_*'

- name: copy common config
  copy:
    src:  '{{ item }}'
    dest: '{{ home_path }}/.ssh/config.d/'
    mode: 0600
  with_fileglob:
    - '_*'

- name: assemble config.d
  assemble:
    src:           '{{ home_path }}/.ssh/config.d'
    dest:          '{{ home_path }}/.ssh/config'
    mode:          0600
    ignore_hidden: yes
    delimiter:     "\n"
