- name: create directories
  file:
    dest:  '{{ home_path }}/{{ item }}'
    mode:  0700
    state: directory
  with_items:
    - '.ssh'
    - '.ssh/config.d'
    - '.ssh/keys'

- name: copy common config
  file:
    src:   '{{ item }}'
    dest: '{{ home_path }}/.ssh/config.d/{{ item | basename }}'
    state: link
    force: yes
    mode: 0600
  with_fileglob:
    - '_*'

- name: assemble config.d
  assemble:
    src:           '{{ home_path }}/.ssh/config.d'
    dest:          '{{ home_path }}/.ssh/config'
    mode:          0600
    ignore_hidden: yes
    delimiter:     "\n"

- name: clone dotssh
  git:
    repo: 'git@github.com:{{ ssh.dotssh }}'
    dest: '{{ src_path }}/github.com/{{ ssh.dotssh }}'
    key_file: '{{ home_path }}/.ssh/id_rsa'
    update: no
  when: ansible_os_family == "Darwin"

- name: install dotssh
  file:
    src:   '{{ item }}'
    dest:  '{{ home_path }}/.ssh/config.d/{{ item | basename }}'
    state: link
    force: yes
    mode: 0600
  with_fileglob:
    - '{{ src_path }}/github.com/{{ ssh.dotssh }}/config.d/_*'
  when: ansible_os_family == "Darwin"

# reassemble
- name: assemble config.d
  assemble:
    src:           '{{ home_path }}/.ssh/config.d'
    dest:          '{{ home_path }}/.ssh/config'
    mode:          0600
    ignore_hidden: yes
    delimiter:     "\n"
