-- DMS (DankMaterialShell) の `dms setup` が配る hyprland.lua (DMS f9eb238) を元にしている。
-- 上流の更新を取り込むときは core/internal/config/embedded/hyprland.lua と見比べる。
-- こちらの上書きは dms/binds-user.lua と dms/outputs.lua、dms/windowrules.lua に置く。
--
-- dms/colors.lua、dms/layout.lua、dms/cursor.lua、dms/windowrules.lua は DMS が設定画面やテーマ変更のたびに
-- 書き換える (初回起動で windowrules.lua は DMS 形式に書き直された)。git では追跡せず、
-- 無ければ飛ばす。ウィンドウルールを自分で足すときは dms/binds-user.lua に書く。
-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })

-- ランチャーから起動したアプリ (Obsidian など) が gh や aqua 管理のツールを見つけられるよう、
-- Hyprland が子プロセスに渡す PATH に .zshenv と同じ先頭 2 つを足す。GDM のセッションは
-- ログインシェルを通らず PAM の PATH のままで、下の startup がそれを systemd に流すので、
-- ここで足さないと systemd 経由の起動 (DMS の systemd-run) 全部に効かない。
local home = os.getenv("HOME")
hl.env("PATH", home .. "/.local/share/aquaproj-aqua/bin:" .. home .. "/.local/bin:" .. (os.getenv("PATH") or ""))
-- aqua が global 設定と policy を見つけるための 2 つも .zshenv と同じにする
-- (実体は store のコピー。modules/home-manager/aqua.nix)
hl.env("AQUA_GLOBAL_CONFIG", ":" .. home .. "/.local/share/aqua-config/aqua.yaml")
hl.env("AQUA_POLICY_CONFIG", home .. "/.local/share/aqua-config/aqua-policy.yaml")

-- DMS_STARTUP_BEGIN
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
end)
-- DMS_STARTUP_END

hl.config({
	input = {
		-- empty inherits XKB_DEFAULT_LAYOUT (libxkbcommon), falls back to "us"
		kb_layout = "",
		numlock_by_default = true,
		follow_mouse = 0,
		touchpad = {
			tap_to_click = true,
			natural_scroll = true,
		},
	},
	general = {
		gaps_in = 5,
		gaps_out = 5,
		border_size = 2,
		layout = "dwindle",
	},
	decoration = {
		rounding = 12,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = true,
			range = 30,
			render_power = 4, -- 雛形は 5 だが nixpkgs の Hyprland 0.56 は上限 4
			offset = "0 5",
			color = "rgba(00000070)",
		},
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
		-- 画面 OFF (DPMS) からの復帰を DMS の idle 復帰通知だけに任せない。DMS はモニタを
		-- 消した側が ext-idle-notify の resumed を受けて点け直す作りなので、消えている間に
		-- DMS が再起動する (home-manager switch など) と、新しい DMS は OFF を知らず、
		-- キーを叩いても誰も点けない状態になる (2026-09-07 phoenix で発生)。
		-- compositor 自身が入力で点ければ DMS の状態に依存しない。
		key_press_enables_dpms = true,
		mouse_move_enables_dpms = true,
		-- 既定 (false) だと xdg-activation の要求を Hyprland が握り潰す。Chrome の
		-- プロファイル切り替えは、そのプロファイルのウィンドウが既にあるときは新規に
		-- 開かず activation を投げるだけなので、false のままだと「切り替え UI を操作しても
		-- 何も起きない」ように見える (実際は切り替わっていて、裏のウィンドウが前に
		-- 来ないだけ)。同じ理由で、外部アプリからリンクを開いたときも既存ウィンドウが
		-- 上がらない。引き換えにどのアプリも focus を奪えるようになるが、意図した
		-- activation が全部死ぬ方が実害が大きい。
		focus_on_activate = true,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
})

hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "default" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "default" })

hl.window_rule({ match = { class = "^(org\\.wezfurlong\\.wezterm)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.)" }, rounding = 12 })
hl.window_rule({ match = { class = "^(gnome-control-center)$" }, tile = true })
hl.window_rule({ match = { class = "^(pavucontrol)$" }, tile = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(gnome-calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(galculator)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Nautilus)$" }, float = true })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
hl.window_rule({
	match = { class = "^(steam)$", title = "^(notificationtoasts)" },
	no_initial_focus = true,
	pin = true,
})
hl.window_rule({
	match = { class = "^(firefox)$", title = "^(Picture-in-Picture)$" },
	float = true,
})
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

pcall(require, "dms.colors")
require("dms.outputs")
pcall(require, "dms.layout")
pcall(require, "dms.cursor")
require("dms.binds")
require("dms.binds-user")
pcall(require, "dms.windowrules")
