anyenv:
  directory: '{{ home_path }}/.anyenv'
  repository: github.com/riywo/anyenv
  plugins_dir: '{{ home_path }}/.anyenv/plugins'
  envs_dir:    '{{ home_path }}/.anyenv/envs'

homebrew:
  repositories:
    - genkiroid/homebrew-cert # for cert

  applications:
    - bettertouchtool
    - caffeine
    - dash
    - docker
    # - dropbox
    - google-chrome
    - google-japanese-ime
    - karabiner-elements
    # - omnifocus
    - postgres
    # - spotify
    - quitter

ssh:
  dotssh: potsbo/dotssh

mas:
  appstore_id: potsbo@gmail.com
  applications:
    1Password 7.app:   '1333542190'
    Fantastical 2.app: '975937182'
    Magnet.app:        '441258766'
    PopClip.app:       '445189367'
    Slack.app:         '803453959'
    # Xcode.app:         '497799835'

ruby:
  versions:
    - 2.7.2
  plugins_dir: '{{ anyenv.envs_dir }}/rbenv/plugins'
  plugins:
    - github.com/sstephenson/rbenv-default-gems
    - github.com/sstephenson/rbenv-gem-rehash
  links:
    ruby/rbenv/default-gems: .anyenv/envs/rbenv/default-gems

python:
  versions:
    - 3.9.1
  packages:
    - numpy

nodejs:
  versions:
    - 14.16.1
  packages:
    - yarn

golang:
  path: '{{ home_path }}/.go'
  versions:
    - 1.14.3
  packages:
    - github.com/izumin5210/gex/cmd/gex
    - github.com/motemen/ghq
    - golang.org/x/tools/cmd/goimports
    - golang.org/x/tools/gopls

tmux:
  directory: '{{ home_path }}/.tmux'
  deps:
    - github.com/potsbo/tmux-powerline

vim:
  directory:  '{{ home_path }}/.vim'
  links:
    vim/indent: .vim/indent
    vim/rc:     .vim/rc
    .vimrc:     .ideavimrc

zsh:
  directory: '{{ home_path }}/.oh-my-zsh'
  manager: github.com/robbyrussell/oh-my-zsh
  plugins:
    - github.com/zsh-users/zsh-syntax-highlighting
    - github.com/zsh-users/zsh-completions
    - github.com/zsh-users/zsh-autosuggestions
    - github.com/bric3/nice-exit-code
  themes:
    - github.com/bhilburn/powerlevel9k
    - github.com/xfanwu/oh-my-zsh-custom-xxf

link:
  bin: bin
  .zshrc:                  .zshrc
  .vimrc:                  .vimrc
  .tigrc:                  .tigrc
  .gitconfig:              .config/git/config
  .gitignore_global:       .config/git/ignore
  .tmux.conf:              .tmux.conf
  .tmux-powerlinerc:       .tmux-powerlinerc
  .bash_profile:           .bash_profile
  init.vim:                .config/nvim/init.vim
  karabiner:               .config/karabiner
  .rubocop.yml:            rubocop.yml
  .clipper.json:           .clipper.json

clone:
  repo: github.com/mzyy94/RictyDiminished-for-Powerline
  dest: '{{ home_path }}/Library/Fonts'
