anyenv:
  directory: '{{ home_path }}/.anyenv'
  repository: github.com/riywo/anyenv
  plugins_dir: '{{ home_path }}/.anyenv/plugins'
  envs_dir:    '{{ home_path }}/.anyenv/envs'

homebrew:
  repositories:
    - genkiroid/homebrew-cert # for cert
    - mscharley/homebrew      # for alacritty

  applications:
    - alacritty
    - alfred
    - atom
    - bettertouchtool
    - caffeine
    - dash
    - docker
    - dropbox
    - google-chrome
    - google-japanese-ime
    - insomnia
    - karabiner-elements
    - postgres
    - skype
    - spotify
    - quitter

  packages:
    - ag
    - autoenv
    - cert
    - creasty/tools/rid
    - dep
    - direnv
    - envchain
    - gnu-sed
    - hub
    - jq
    - mas
    - neovim
    - nodejs
    - peco
    - protobuf
    - reattach-to-user-namespace
    - tmux
    - tig
    - tree
    - wget
    - watch

ssh:
  dotssh: potsbo/dotssh

mas:
  appstore_id: potsbo@gmail.com
  applications:
    1Password 7.app:   '1333542190'
    Fantastical 2.app: '975937182'
    Magnet.app:        '441258766'
    OmniFocus.app:     '867299399'
    PopClip.app:       '445189367'
    Quiver.app:        '866773894'
    Slack.app:         '803453959'
    Spark.app:         '1176895641'
    Xcode.app:         '497799835'

ruby:
  versions:
    - 2.6.0
    - 2.5.1
  plugins_dir: '{{ anyenv.envs_dir }}/rbenv/plugins'
  plugins:
    - github.com/sstephenson/rbenv-default-gems
    - github.com/sstephenson/rbenv-gem-rehash
  links:
    ruby/rbenv/default-gems: .anyenv/envs/rbenv/default-gems

python:
  versions:
    - 3.6.5
  packages:
    - numpy

nodejs:
  versions:
    - 8.12.0
  packages:
    - yarn

golang:
  path: '{{ home_path }}/.go'
  versions:
    - 1.12.6
    - 1.11.1
  packages:
    - github.com/izumin5210/gex/cmd/gex
    - github.com/motemen/ghq
    - golang.org/x/tools/cmd/gopls

tmux:
  directory: '{{ home_path }}/.tmux'
  deps:
    - github.com/potsbo/tmux-powerline

vim:
  directory:  '{{ home_path }}/.vim'
  links:
    vim/indent: .vim/indent
    vim/rc:     .vim/rc
    .vimrc:     .ideavimrc

zsh:
  directory: '{{ home_path }}/.oh-my-zsh'
  manager: github.com/robbyrussell/oh-my-zsh
  plugins:
    - github.com/zsh-users/zsh-syntax-highlighting
    - github.com/zsh-users/zsh-completions
    - github.com/zsh-users/zsh-autosuggestions
    - github.com/bric3/nice-exit-code
  themes:
    - github.com/bhilburn/powerlevel9k
    - github.com/xfanwu/oh-my-zsh-custom-xxf

link:
  bin: bin
  .zshrc:                  .zshrc
  .vimrc:                  .vimrc
  .gitconfig:              .gitconfig
  .gitignore_global:       .gitignore_global
  .tmux.conf:              .tmux.conf
  .tmux-powerlinerc:       .tmux-powerlinerc
  .bash_profile:           .bash_profile
  .dein.toml:              .dein.toml
  .dein.lazy.toml:         .dein.lazy.toml
  init.vim:                .config/nvim/init.vim
  karabiner:               .config/karabiner
  alacritty:               .config/alacritty
  .rubocop.yml:            rubocop.yml

clone:
  repo: github.com/mzyy94/RictyDiminished-for-Powerline
  dest: '{{ home_path }}/Library/Fonts'
