- name:       development environment
  hosts:      127.0.0.1
  connection: local
  vars:
    home_path:     '{{ lookup("env", "HOME") }}'
    dotfiles_path: '{{ home_path }}/.dotfiles'
    src_path: '{{ home_path }}/.go/src'

  environment:
    PATH: '/usr/local/bin:{{ anyenv.directory }}/bin:{{ anyenv.envs_dir }}/rbenv/shims:{{ anyenv.envs_dir }}/ndenv/shims:{{ anyenv.envs_dir }}/pyenv/shims:{{ anyenv.envs_dir }}/goenv/shims:{{ lookup("env", "PATH") }}'
    GOPATH: '{{ golang.path }}'

  vars_files:
    - config.yml

  roles:
    - role: ssh
      tags: ['basic', 'ssh']

    - role: homebrew
      tags: ['install', 'homebrew']

    - role: mas
      tags: ['install', 'mas', 'osx']

    - role: tmux
      tags: ['install', 'tmux']

    - role: zsh
      tags: ['install', 'zsh']

    - role: vim
      tags: ['install', 'vim']

    - role: osx
      tags: ['osx']

    - role: clone
      tags: ['clone']
