- name:       development environment
  hosts:      127.0.0.1
  connection: local
  vars:
    home_path:     '{{ lookup("env", "HOME") }}'
    dotfiles_path: '{{ home_path }}/.dotfiles'
    src_path: '{{ home_path }}/.go/src'

  environment:
    PATH: '/usr/local/bin:{{ anyenv.directory }}/bin:{{ anyenv.envs_dir }}/rbenv/shims:{{ anyenv.envs_dir }}/ndenv/shims:{{ anyenv.envs_dir }}/pyenv/shims:{{ anyenv.envs_dir }}/goenv/shims:{{ lookup("env", "PATH") }}'

  vars_files:
    - config.yml

  roles:
    - role: link
      tags: ['basic', 'link']

    - role: ssh
      tags: ['basic', 'ssh']

    - role: anyenv
      tags: ['install', 'anyenv']

    - role: homebrew
      tags: ['install', 'homebrew']

    - role: mas
      tags: ['install', 'mas']

    - role: ruby
      tags: ['language', 'ruby']

    - role: golang
      tags: ['language', 'golang']

    - role: rust
      tags: ['language', 'rust']

    - role: python
      tags: ['language', 'python']

    - role: nodejs
      tags: ['language', 'nodejs']

    - role: tmux
      tags: ['install', 'tmux']

    - role: zsh
      tags: ['install', 'zsh']

    - role: vim
      tags: ['install', 'vim']

    - role: osx
      tags: ['osx']

    - role: clone
      tags: ['clone']
