- name: check rbenv
  command: |
    bash -lc 'which rbenv'
  register: which_rbenv
  ignore_errors: yes

- name: install rbenv
  command: |
    bash -lc 'anyenv install rbenv'
  when: which_rbenv.rc > 0

- name: get installed versions
  command: |
    bash -lc 'rbenv versions'
  register: installed_versions

- name: install ruby
  command: |
    bash -lc 'rbenv install {{ item | quote }}'
  when: |
    ruby.versions and installed_versions.stdout.find(item) == -1
  with_items: '{{ ruby.versions }}'
