name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install aqua
        uses: aquaproj/aqua-installer@v4.0.4
        with:
          aqua_version: v2.56.7
      - run: ./install
      - run: aqua install

  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@v3
      - run: nix build ./nix#homeConfigurations.linux.activationPackage
